### Create a new game
POST http://localhost:3000/api/game/create
Content-Type: application/json

{
  "player1ID": "user1",
  "player2ID": "user2",
  "roomId": "room123"
}
### Make a move in a game
POST http://localhost:3000/api/game/game-509srsome/move
Content-Type: application/json

{
  "playerID": "user1",
  "move": {
    "row": 0,
    "col": 1
  }
}