### Create a new game
@baseUrl = http://localhost:3002

GET {{baseUrl}}/api/game
Content-Type: application/json

### Create a new game
POST {{baseUrl}}/api/game/create
Content-Type: application/json

{
  "player1ID": "user1",
  "player2ID": "user2",
  "roomId": "room123"
}
### Make a move in a game
POST {{baseUrl}}/api/game/game-iuhc79lnw/move
Content-Type: application/json

{
  "playerID": "user1",
  "move": {
    "row": 0,
    "col": 1
  }
}